routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
  Route::resource('masjid', 'MasjidController');
  Route::resource('kas', 'KasController');
  Route::resource('acara', 'AcaraController');
  Route::resource('karangan', 'KaranganController');
  Route::resource('laporan', 'LaporanController');

  
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Acara.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Acara extends Model{
    protected $table = 'acara';
    protected $primaryKey = 'id_acara';
        protected $fillable = [
        'nama_acara','pict','status','id_masjid'
    ];
}

?>

app/Http/Controllers/AcaraController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Masjid;
use App\Acara;
use Auth;
class AcaraController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cekauth = Auth::user()->hak_akses;
        if ($cekauth == 'administrator') {
            $data = Acara::paginate('10');
            
            foreach ($data as $item) {
                $item->masjid = Masjid::find($item->id_masjid);
            }
            
        $tampil['data'] = $data;
            return view('acara.index',$tampil);
            // dd($tampil); 
        } else {
            $id = Auth::id();
            $cekmasjid = Masjid::where('id_user', $id)->first();
            $data = Acara::where('id_masjid', $cekmasjid->id_masjid)->paginate('10');
            foreach ($data as $item) {
                $item->masjid = Masjid::find($item->id_masjid);
            }
            $tampil['data'] = $data;
            return view('acara.index',$tampil);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cekauth = Auth::user()->hak_akses;
        if ($cekauth == 'administrator') {
            $data['masjid'] = Masjid::get();
       
            return view('acara.create',$data);
            // dd($tampil); 
        } else {
            $id = Auth::id();
            $cekmasjid = Masjid::where('id_user', $id)->first();
            $data['masjid'] = Masjid::where('id_masjid', $cekmasjid->id_masjid)->get();
            
            return view('acara.create',$data);
        }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'nama_acara' => 'required',
            'status' => 'required',
            'pict' => 'required',
            'id_masjid' => 'required',
        ]);

        $nama = Auth::user()->name;
        $file = $request->file('pict');
        if ($file !='') {
            $file = $request->file('pict');
            $extension=$file->getClientOriginalExtension();
            $destinationPath = 'assets/picture';
            $fileName = rand(11111, 99999) . '.' . $extension;
            $request->file('pict')->move($destinationPath, $fileName);
            $data = Acara::insert([
                'pict' => $fileName,
                'nama_acara' => $request->nama_acara,
                'id_masjid' => $request->id_masjid,
                'status' => $request->status
            ]);
        }else{
            $data = Acara::insert([
                'nama_acara' => $request->nama_acara,
                'id_masjid' => $request->id_masjid,
                'status' => $request->status
            ]);
        }
        return redirect()->route("acara.index")->with(
            "success",
            "Data berhasil disimpan."
            );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cekauth = Auth::user()->hak_akses;
        if ($cekauth == 'administrator') {
            $data = Acara::findOrfail($id);
            $data->masjid = Masjid::get();
            return view('acara.edit',$data);
            // dd($data); 
        } else {
            $id_user = Auth::id();
            $cekmasjid = Masjid::where('id_user', $id_user)->first();
            $data = Acara::findOrfail($id);
            $data->masjid = Masjid::where('id_masjid', $cekmasjid->id_masjid)->get();
            
            return view('acara.edit',$data);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_acara' => 'required',
            'status' => 'required',
            'id_masjid' => 'required',
        ]);

        $nama = Auth::user()->name;
        $file = $request->file('pict');
        if ($file !='') {
            $file = $request->file('pict');
            $extension=$file->getClientOriginalExtension();
            $destinationPath = 'assets/picture';
            $fileName = rand(11111, 99999) . '.' . $extension;
            $request->file('pict')->move($destinationPath, $fileName);
            $data = Acara::where('id_acara',$id)
            ->update([
                'pict' => $fileName,
                'nama_acara' => $request->nama_acara,
                'id_masjid' => $request->id_masjid,
                'status' => $request->status
            ]);
        }else{
            $data = Acara::where('id_acara',$id)
            ->update([
                'nama_acara' => $request->nama_acara,
                'id_masjid' => $request->id_masjid,
                'status' => $request->status
            ]);
        }
        return redirect()->route("acara.index")->with(
            "success",
            "Data berhasil disimpan."
            );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dataAcara = Acara::findOrFail($id);
        $dataAcara->delete();
    }
}

resources/views/acara/create.blade.php
@extends('adminlte::page')
@section('title','acara')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen acara</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Tambah acara
                </div>
                <div class="card-body">
                    <form action="{{ route('acara.store') }}" enctype="multipart/form-data" method="post" class="form-horizontal">
                        @include('acara.form')
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    @section('plugins.Pace', true)
   

resources/views/acara/edit.blade.php
@extends('adminlte::page')
@section('title','Acara')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Acara</h1>
    @endsection
@section('content')

<div class="row">
        <div class="col-12">
            @if($errors->any())
            <div class="alert alert-warning alert-dismissable">
                <button class="close" type="button" data-dismiss="alert" aria-hidden="true">x</button>
                <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Ubah Acara
                </div>
                <div class="card-body">
                    <form action = "{{ route('acara.update', $id_acara ?? '') }}" class="form-horizontal" method="post" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                          <div class="form-group">
                            <label for="id_masjid" class="col-sm-2 cotrol-label">masjid</label>
                            <div class="col-sm-10">
                                <select name="id_masjid" class="form-control">
                                    @foreach ($masjid as $item)
                                        <option value="{{ $item->id_masjid }}" {{ ( ($id_masjid ?? ''   ) == $item->id_masjid ) ? 'selected' : '' }}>
                                            {{ $item->id_masjid }} - {{ $item->nama_masjid }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="nama_acara" class="col-sm-2 cotrol-label">Acara</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="nama_acara" value="{{ $nama_acara ?? ''  }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-xl-3 col-lg-3 col-form-label">Foto </label>
                            <div class="col-lg-9 col-xl-6">
                                <img class="kt-avatar__holder" src="/assets/picture/{{$pict}}" id="showgambar" style="height:300px;" alt="">
                                <input type="file" id="inputgambar" name="pict" value="{{$pict}}" class="validate"/ >
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Status">Status</label>
                            <select class="form-control" name="status">
                                <option value="publish" @if ($status == 'publish' )
                                    selected>
                                    Publish
                                </option>
                                <option value="hide">Hide</option>
                                @else
                                <option value="hide" selected>Hide</option>
                                <option value="publish">Publish</option>
                                
                                @endif
                            </select>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-2">
                                <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
                                <a href="{{ route('acara.index') }}" role="button" class="btn btn-primary">Batal</a>
                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>

        </div>
    </div>

 @endsection
 @section('plugins.Pace', true)
 @section('js')
 <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

 <script type="text/javascript">

    function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
              $('#showgambar').attr('src', e.target.result);
          }

          reader.readAsDataURL(input.files[0]);
      }
  }

  $("#inputgambar").change(function () {
      readURL(this);
  });


</script>

resources/views/acara/form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="id_masjid" class="col-sm-2 cotrol-label">Masjid</label>
    <div class="col-sm-10">
        <select name="id_masjid" class="form-control">
            @foreach ($masjid as $item)
                <option value="{{ $item->id_masjid }}" {{ ( ($id_masjid ?? ''   ) == $item->id_masjid ) ? 'selected' : '' }}>
                    {{ $item->id_masjid }} - {{ $item->nama_masjid }}
                </option>
            @endforeach
        </select>
    </div>
</div>
<div class="form-group">
    <label for="nama_acara" class="col-sm-2 cotrol-label">Acara</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="nama_acara" value="{{ $nama_acara ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <label for="pict" class="col-sm-2 cotrol-label">Banner</label>
    <div class="col-sm-10">
        <input type="file" class="form-control" name="pict" value="{{ $pict ?? ''  }}">
    </div>
</div>

<div class="form-group">
    <label for="status" class="col-sm-2 cotrol-label">Status</label>
    <div class="col-sm-10">
        <select name="status" class="form-control">
            <option value="hide"> Hide </option>
            <option value="publish"> Publish </option>
        </select>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('acara.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>

resources/views/acara/index.blade.php
@extends('adminlte::page')

@section('title','acara')

@section('content_header')
<h1 class="m-0 text-dark">Manajemen acara</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-header">
                    <a href="{{ route('acara.create') }}" class="btn btn-primary btn-md">
                        <i class="fa fa-plus"> Tambah</i>
                    </a>                        
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th style="width: 20px">#</th>
                                <th> pict</th>
                                <th>nama acara</th>
                                <th> status</th>
                                <th> id - Nama Masjid</th>
                                <th style="width: 80px"> Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $no= 1 ; ?>
                            @forelse ($data as $item)
                                <tr>
                                    <td>
                                        {{ $no }}
                                    </td>
                                    <td>
                                        <img src="{{ url('assets/picture/'. $item->pict)}}" width="100px" alt="image" style="margin-right: 10px;" />
                                    </td>
                                    <td>
                                        {{ $item->nama_acara }}
                                    </td>
                                    <td>
                                        {{ $item->status }}
                                    </td>
                                    <td>
                                        {{ $item->masjid->id_masjid }} - {{ $item->masjid->nama_masjid }}
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="{{ route('acara.edit', $item->id_acara) }}" class="btn btn-success">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                            <a onclick="hapus('{{ $item->id_acara }}')" href="#" class="btn btn-primary">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <?php $no++; ?>
                            @empty
                                <tr>
                                    <td colspan="6">
                                        Tidak Ada Data
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix text-right">
                    {{ $data->links() }}
                </div>

            </div>
        </div>
    </div>
    @stop

    @section('plugins.Sweetalert2', true)
    @section('plugins.Pace',true)
    
    @section('js')
        @if (session('success'))
            <script type="text/javascript">
                Swal.fire(
                    'Sukses!',
                    '{{ session('success') }}',
                    'success'
                )
            </script>
        @endif
            <script type="text/javascript">
                function hapus(id){
                    Swal.fire({
                        title : 'Konfirmasi',
                        text : "Yakin ingin menghapus data ini ?",
                        icon : 'warning',
                        showCancelButton : true,
                        confirmButtonColor : '#3085d6',
                        cancelButtonColor: '#dd3333',
                        confirmButtonText: 'Hapus',
                        cancelButtonText: 'Batal',
                    }).then((result) =>  {
                        if (result.value){
                            $.ajax({
                                url: "/acara/"+id,
                                type: 'DELETE',
                                data:{
                                    '_token' : $('meta[name=csrf-token]').attr("content"),
                                },
                                success : function(result){
                                    Swal.fire(
                                        'Sukses!',
                                        'Berhasil dihapus',
                                        'success'
                                    );
                                    location.reload();
                                }
                            })
                        }
                    })
                }
            </script>
            @stop