routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
  Route::resource('masjid', 'MasjidController');
  Route::resource('kas', 'KasController');
  Route::resource('acara', 'AcaraController');
  Route::resource('karangan', 'KaranganController');
  Route::resource('laporan', 'LaporanController');

  
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Masjid.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Masjid extends Model{
    protected $table = 'masjid';
    protected $primaryKey = 'id_masjid';
        protected $fillable = [
        'nama_masjid','alamat','no_rekening','no_telpon','id_user'
    ];
}

?>

app/Http/Controllers/MasjidController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Masjid;
use App\User;
use Auth;

class MasjidController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $cekauth = Auth::user()->hak_akses;
        if ($cekauth == 'administrator') {
            $data = Masjid::paginate('10');
            
            foreach ($data as $item ){
                $item->user = User::find($item->id_user);
            }
            $tampil['data'] = $data;
            return view('masjid.index', $tampil);
        
        } else {
            $id = Auth::id();
            $cekmasjid = Masjid::where('id_user', $id)->first();
            $data = Masjid::where('id_masjid', $cekmasjid->id_masjid)->paginate('10');
            foreach ($data as $item ){
                $item->user = User::find($item->id_user);
            }
            $tampil['data'] = $data;
            return view('masjid.index',$tampil);
        }
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['user'] = User::where('hak_akses', 'petugas')->get();
        return view('masjid.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validasi inputan
        $this->validate($request, [
            'nama_masjid' => 'required',
            'alamat' => 'required',
            'no_telpon' => 'required',
            'no_rekening' => 'required',
            'id_user' => 'required|unique:masjid',
            ]);

            $dataMasjid = Masjid::create($request->all());
            return redirect()->route("masjid.index")->with(
            "success",
            "Data berhasil disimpan."
            ); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cekauth = Auth::user()->hak_akses;
        if ($cekauth == 'administrator') {
           
        $data = Masjid::findOrFail($id);
        $data->user = User::where('hak_akses', 'petugas')->get();

        //tampilkan resources/views/Jamaat/edit.blade.php
        return view("masjid.edit", $data);

        } else {
            $id_user = Auth::id();
            $cekmasjid = Masjid::where('id_user', $id_user)->first();
            $data = Masjid::findOrFail($id);
            $data->user = User::where('hak_akses', 'petugas')
            ->where('id',$cekmasjid->id_user)
            ->get();

        //tampilkan resources/views/Jamaat/edit.blade.php
        return view("masjid.edit", $data);

        }




    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         //validasi inputan
         $this->validate($request, [
            'nama_masjid' => 'required',
            'alamat' => 'required',
            'no_telpon' => 'required',
            'no_rekening' => 'required',
            'id_user' => 'required|unique:masjid',
            ]);

            $dataMasjid = Masjid::findOrFail($id);
            $dataMasjid->nama_masjid = $request->nama_masjid;
            $dataMasjid->alamat = $request->alamat;
            $dataMasjid->no_rekening = $request->no_rekening;
            $dataMasjid->no_telpon = $request->no_telpon;
            $dataMasjid->id_user = $request->id_user;
            $dataMasjid->save();

         
        return redirect()->route("masjid.index")->with(
        "success",
        "Data berhasil diubah."
        ); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dataMasjid = Masjid::findOrFail($id);
            $dataMasjid->delete();
    }
}

resources/views/masjid/create.blade.php
@extends('adminlte::page')
@section('title','masjid')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen masjid</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Tambah masjid
                </div>
                <div class="card-body">
                    <form action="{{ route('masjid.store') }}" method="post" class="form-horizontal">
                        @include('masjid.form')
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    @section('plugins.Pace',true)

resources/views/masjid/edit.blade.php
@extends('adminlte::page')
@section('title','Masjid')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Masjid</h1>
    @endsection
@section('content')
    <div class="row">
        <div class="col-12">
            @if($errors->any())
            <div class="alert alert-warning alert-dismissable">
                <button class="close" type="button" data-dismiss="alert" aria-hidden="true">x</button>
                <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Ubah Masjid
                </div>
                <div class="card-body">
                    <form action = "{{ route('masjid.update', $id_masjid ?? '') }}" class="form-horizontal" method="post">
                        @method('PUT')
                        @csrf

                        <div class="form-group">
                            <label for="nama_masjid" class="col-sm-2 cotrol-label">Nama Masjid</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="nama_masjid" value="{{ $nama_masjid ?? ''  }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="alamat" class="col-sm-2 cotrol-label">Alamat</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="alamat" value="{{ $alamat ?? ''  }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="no_rekening" class="col-sm-2 cotrol-label">No Rekening</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="no_rekening" value="{{ $no_rekening ?? ''  }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="no_telpon" class="col-sm-2 control-label">No Telpon</label>
                            <div class="col-sm-10">
                                <input type="text" name="no_telpon" class="form-control" value="{{ $no_telpon ?? '' }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_user" class="col-sm-2 cotrol-label">Petugas</label>
                            <div class="col-sm-10">
                                <select name="id_user" class="form-control">
                                    @foreach ($user as $item)
                                        <option value="{{ $item->id }}" {{ ( ($id_user ?? ''   ) == $item->id ) ? 'selected' : '' }}>
                                            {{ $item->id }} - {{ $item->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div> 
                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-2">
                                <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
                                <a href="{{ route('masjid.index') }}" role="button" class="btn btn-primary">Batal</a>
                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>

        </div>
    </div>
 @endsection
 @section('plugins.Pace',true)

resources/views/masjid/form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="nama_masjid" class="col-sm-2 cotrol-label">Nama Masjid</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="nama_masjid" value="{{ $nama_masjid ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <label for="alamat" class="col-sm-2 cotrol-label">Alamat</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="alamat" value="{{ $alamat ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <label for="no_rekening" class="col-sm-2 cotrol-label">No Rekening</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="no_rekening" value="{{ $no_rekening ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <label for="no_telpon" class="col-sm-2 control-label">No Telpon</label>
    <div class="col-sm-10">
        <input type="text" name="no_telpon" class="form-control" value="{{ $no_telpon ?? '' }}">
    </div>
</div>
<div class="form-group">
    <label for="id_user" class="col-sm-2 cotrol-label">Petugas</label>
    <div class="col-sm-10">
        <select name="id_user" class="form-control">
            @foreach ($user as $item)
                <option value="{{ $item->id }}" {{ ( ($id_user ?? ''   ) == $item->id ) ? 'selected' : '' }}>
                    {{ $item->id }} - {{ $item->name }}
                </option>
            @endforeach
        </select>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('masjid.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>

resources/views/masjid/index.blade.php
@extends('adminlte::page')

@section('title','masjid')

@section('content_header')
<h1 class="m-0 text-dark">Manajemen masjid</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-header">
                    @if (Auth::user() === "admin" )
                    <a href="{{ route('masjid.create') }}" class="btn btn-primary btn-md">
                        <i class="fa fa-plus"> Tambah</i>
                    </a>       
                    @else
                        
                    @endif
                                         
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th style="width: 20px">#</th>
                                <th> nama masjid</th>
                                <th> alamat</th>
                                <th> no.telpon - no.rekening</th>
                                <th> petugas</th>
                                <th style="width: 80px"> Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $no= 1 ; ?>
                            @forelse ($data as $item)
                                <tr>
                                    <td>
                                        {{ $no }}
                                    </td>
                                    <td>
                                        {{ $item->nama_masjid }}
                                    </td>
                                    <td>
                                        {{ $item->alamat }}
                                    </td>
                                    <td>
                                        {{ $item->no_telpon }} - {{ $item->no_rekening }}
                                    </td>
                                    <td>
                                        {{ $item->user->id }} - {{ $item->user->name }}
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="{{ route('masjid.edit', $item->id_masjid) }}" class="btn btn-success">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                            @if (Auth::user() === "admin" )
                                            <a onclick="hapus('{{ $item->id_masjid }}')" href="#" class="btn btn-primary">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                            @else
                                            @endif
                                        </div>
                                    </td>
                                </tr>
                                <?php $no++; ?>
                            @empty
                                <tr>
                                    <td colspan="6">
                                        Tidak Ada Data
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix text-right">
                    {{ $data->links() }}
                </div>

            </div>
        </div>
    </div>
    @stop

    @section('plugins.Sweetalert2', true)
    @section('plugins.Pace',true)
    
    @section('js')
        @if (session('success'))
            <script type="text/javascript">
                Swal.fire(
                    'Sukses!',
                    '{{ session('success') }}',
                    'success'
                )
            </script>
        @endif
            <script type="text/javascript">
                function hapus(id){
                    Swal.fire({
                        title : 'Konfirmasi',
                        text : "Yakin ingin menghapus data ini ?",
                        icon : 'warning',
                        showCancelButton : true,
                        confirmButtonColor : '#3085d6',
                        cancelButtonColor: '#dd3333',
                        confirmButtonText: 'Hapus',
                        cancelButtonText: 'Batal',
                    }).then((result) =>  {
                        if (result.value){
                            $.ajax({
                                url: "/masjid/"+id,
                                type: 'DELETE',
                                data:{
                                    '_token' : $('meta[name=csrf-token]').attr("content"),
                                },
                                success : function(result){
                                    Swal.fire(
                                        'Sukses!',
                                        'Berhasil dihapus',
                                        'success'
                                    );
                                    location.reload();
                                }
                            })
                        }
                    })
                }
            </script>
            @stop