routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
  Route::resource('masjid', 'MasjidController');
  Route::resource('kas', 'KasController');
  Route::resource('acara', 'AcaraController');
  Route::resource('karangan', 'KaranganController');
  Route::resource('laporan', 'LaporanController');

  
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Kas.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Kas extends Model{
    protected $table = 'kas_masjid';
    protected $primaryKey = 'id_kas';
        protected $fillable = [
        'uang_masuk','uang_keluar','tanggal','catatan','id_masjid'
    ];

    
    protected $dates = ['tanggal'];
}

?>

app/Http/Controllers/KasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\User;
use App\Kas;
use App\Masjid;


class KasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cekauth = Auth::user()->hak_akses;
        if ($cekauth == 'administrator') {
            $data = Kas::paginate('10');
            
            foreach ($data as $item) {
                $item->masjid = Masjid::find($item->id_masjid);
            }
            
        $tampil['data'] = $data;
            return view('kas.index',$tampil);
            // dd($tampil); 
        } else {
            $id = Auth::id();
            $cekmasjid = Masjid::where('id_user', $id)->first();
            $data = Kas::where('id_masjid', $cekmasjid->id_masjid)->paginate('10');
            foreach ($data as $item) {
                $item->masjid = Masjid::find($item->id_masjid);
            }
            $tampil['data'] = $data;
            return view('kas.index',$tampil);
            // dd($data);
        }
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cekauth = Auth::user()->hak_akses;
        if ($cekauth == 'administrator') {
            $data['masjid'] = Masjid::get();
       
            return view('kas.create',$data);
            // dd($tampil); 
        } else {
             $id = Auth::id();
            $cekmasjid = Masjid::where('id_user', $id)->first();
            $data['masjid'] = Kas::where('id_masjid', $cekmasjid->id_masjid)->get();
            
            return view('kas.create',$data);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         //validasi inputan
         $this->validate($request, [
            'tanggal' => 'required',
            'id_masjid' => 'required',
            'catatan' => 'required'
            ]);

            $dataKas = Kas::create($request->all());
            return redirect()->route("kas.index")->with(
            "success",
            "Data berhasil disimpan."
            );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cekauth = Auth::user()->hak_akses;
        if ($cekauth == 'administrator') {
            $data = Kas::findOrfail($id);
            $data->masjid = Masjid::get();
            return view('kas.edit',$data);
            // dd($tampil); 
        } else {
            $id_user = Auth::id();
            $cekmasjid = Masjid::where('id_user', $id_user)->first();
            $data = Kas::findOrfail($id);
            $data->masjid = Masjid::where('id_masjid', $cekmasjid->id_masjid)->get();
            
            return view('kas.edit',$data);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validasi inputan
        $this->validate($request, [
            'tanggal' => 'required',
            'id_masjid' => 'required',
            'catatan' => 'required'
            ]);

            $dataKas = Kas::findOrFail($id);
            $dataKas->id_masjid = $request->id_masjid;
            $dataKas->tanggal = $request->tanggal;
            $dataKas->uang_keluar = $request->uang_keluar;
            $dataKas->catatan = $request->catatan;
            $dataKas->save();

         
        return redirect()->route("kas.index")->with(
        "success",
        "Data berhasil diubah."
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $datakas = Kas::findOrFail($id);
        $datakas->delete();
    }
}

resources/views/kas/create.blade.php
@extends('adminlte::page')
@section('title','kas')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen kas</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Tambah kas
                </div>
                <div class="card-body">
                    <form action="{{ route('kas.store') }}" method="post" class="form-horizontal">
                        @include('kas.form')
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    
    @section('plugins.Pace', true)
    @section('plugins.DateRangePicker', true)
    @section('js')
   
    <script>
       $(function() {
         $('input[name="tanggal"]').daterangepicker({
           singleDatePicker: true,
           showDropdowns: true,
           minYear: 1901,
           maxYear: parseInt(moment().format('YYYY'),10)
         }); 
       });
       </script>
    @stop

resources/views/kas/edit.blade.php
@extends('adminlte::page')
@section('title','Kas')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Kas</h1>
    @endsection
@section('content')

<div class="row">
        <div class="col-12">
            @if($errors->any())
            <div class="alert alert-warning alert-dismissable">
                <button class="close" type="button" data-dismiss="alert" aria-hidden="true">x</button>
                <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Ubah Kas
                </div>
                <div class="card-body">
                    <form action = "{{ route('kas.update', $id_kas ?? '') }}" class="form-horizontal" method="post">
                        @method('PUT')
                        @csrf
                          <div class="form-group">
                            <label for="id_masjid" class="col-sm-2 cotrol-label">masjid</label>
                            <div class="col-sm-10">
                                <select name="id_masjid" class="form-control">
                                    @foreach ($masjid as $item)
                                        <option value="{{ $item->id_masjid }}" {{ ( ($id_masjid ?? ''   ) == $item->id_masjid ) ? 'selected' : '' }}>
                                            {{ $item->id_masjid }} - {{ $item->nama_masjid }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="tanggal" class="col-sm-2 cotrol-label">Tanggal</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="tanggal" name="tanggal" value="{{ \Carbon\Carbon::parse($item->tanggal)->format('m/d/Y') ?? '' }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="uang_masuk" class="col-sm-2 cotrol-label">Uang Masuk</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="uang_masuk" value="{{ $uang_masuk ?? ''  }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="uang_keluar" class="col-sm-2 cotrol-label">Uang keluar</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="uang_keluar" value="{{ $uang_keluar ?? ''  }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="catatan" class="col-sm-2 control-label">Catatan</label>
                            <div class="col-sm-10">
                                <input type="text" name="catatan" class="form-control" value="{{ $catatan ?? '' }}">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-2">
                                <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
                                <a href="{{ route('kas.index') }}" role="button" class="btn btn-primary">Batal</a>
                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>

        </div>
    </div>
 @endsection
 @section('plugins.Pace', true)
 @section('plugins.DateRangePicker', true)
 @section('js')

 <script>
    $(function() {
      $('input[name="tanggal"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
        minYear: 1901,
        maxYear: parseInt(moment().format('YYYY'),10)
      }); 
    });
    </script>
 @stop

resources/views/kas/form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="id_masjid" class="col-sm-2 cotrol-label">Masjid</label>
    <div class="col-sm-10">
        <select name="id_masjid" class="form-control">
            @foreach ($masjid as $item)
                <option value="{{ $item->id_masjid }}" {{ ( ($id_masjid ?? ''   ) == $item->id_masjid ) ? 'selected' : '' }}>
                    {{ $item->id_masjid }} - {{ $item->nama_masjid }}
                </option>
            @endforeach
        </select>
    </div>
</div>
<div class="form-group">
    <label for="tanggal" class="col-sm-2 cotrol-label">Tanggal</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" id="tanggal" name="tanggal" value="{{ $tanggal ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <label for="uang_masuk" class="col-sm-2 cotrol-label">Uang Masuk</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="uang_masuk" value="{{ $uang_masuk ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <label for="uang_keluar" class="col-sm-2 cotrol-label">Uang Keluar</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="uang_keluar" value="{{ $uang_keluar ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <label for="catatan" class="col-sm-2 control-label">Catatan</label>
    <div class="col-sm-10">
        <input type="text" name="catatan" class="form-control" value="{{ $catatan ?? '' }}">
    </div>
</div>

<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('kas.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>

resources/views/kas/index.blade.php
@extends('adminlte::page')

@section('title','kas')

@section('content_header')
<h1 class="m-0 text-dark">Manajemen kas</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-header">
                    <a href="{{ route('kas.create') }}" class="btn btn-primary btn-md">
                        <i class="fa fa-plus"> Tambah</i>
                    </a>                        
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th style="width: 20px">#</th>
                                <th> tanggal</th>
                                <th> id - Nama Masjid</th>
                                <th>uang masuk</th>
                                <th>uang keluar</th>
                                <th> catatan</th>
                                
                                <th style="width: 80px"> Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $no= 1 ; ?>
                            @forelse ($data as $item)
                                <tr>
                                    <td>
                                        {{ $no }}
                                    </td>
                                    <td>
                                         {{ \Carbon\Carbon::parse($item->tanggal)->format('d/m/Y')}}
                                    </td>
                                    <td>
                                        {{ $item->masjid->id_masjid }} - {{ $item->masjid->nama_masjid }}
                                    </td>
                                    
                                    <td>
                                        {{ $item->uang_masuk }}
                                    </td>
                                    <td>
                                        {{ $item->uang_keluar }}
                                    </td>
                                    <td>
                                        {{ $item->catatan }}
                                    </td>
                                    
                                    <td>
                                        <div class="btn-group">
                                            <a href="{{ route('kas.edit', $item->id_kas) }}" class="btn btn-success">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                            <a onclick="hapus('{{ $item->id_kas }}')" href="#" class="btn btn-primary">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <?php $no++; ?>
                            @empty
                                <tr>
                                    <td colspan="7">
                                        Tidak Ada Data
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix text-right">
                    {{ $data->links() }}
                </div>

            </div>
        </div>
    </div>
    @stop

    @section('plugins.Sweetalert2', true)
    @section('plugins.Pace',true)
    
    @section('js')
        @if (session('success'))
            <script type="text/javascript">
                Swal.fire(
                    'Sukses!',
                    '{{ session('success') }}',
                    'success'
                )
            </script>
        @endif
            <script type="text/javascript">
                function hapus(id){
                    Swal.fire({
                        title : 'Konfirmasi',
                        text : "Yakin ingin menghapus data ini ?",
                        icon : 'warning',
                        showCancelButton : true,
                        confirmButtonColor : '#3085d6',
                        cancelButtonColor: '#dd3333',
                        confirmButtonText: 'Hapus',
                        cancelButtonText: 'Batal',
                    }).then((result) =>  {
                        if (result.value){
                            $.ajax({
                                url: "/kas/"+id,
                                type: 'DELETE',
                                data:{
                                    '_token' : $('meta[name=csrf-token]').attr("content"),
                                },
                                success : function(result){
                                    Swal.fire(
                                        'Sukses!',
                                        'Berhasil dihapus',
                                        'success'
                                    );
                                    location.reload();
                                }
                            })
                        }
                    })
                }
            </script>
            @stop